FL Paper Experiment | INFO flwr 2024-03-19 13:14:30,447 | main.py:35 | 
================================================================================
CIFAR10 - FedProx - NonIID Distribution has started
================================================================================
FL Paper Experiment | INFO flwr 2024-03-19 13:14:30,448 | app.py:178 | Starting Flower simulation, config: ServerConfig(num_rounds=40, round_timeout=None)
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,540 | app.py:213 | Flower VCE: Ray initialized with resources: {'node:172.18.144.40': 1.0, 'memory': 7390455399.0, 'object_store_memory': 3695227699.0, 'node:__internal_head__': 1.0, 'CPU': 6.0}
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,541 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,541 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 4, 'num_gpus': 0}
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,547 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,548 | server.py:89 | Initializing global parameters
FL Paper Experiment | INFO flwr 2024-03-19 13:14:32,548 | server.py:276 | Requesting initial parameters from one random client
FL Paper Experiment | INFO flwr 2024-03-19 13:14:35,582 | server.py:280 | Received initial parameters from one random client
FL Paper Experiment | INFO flwr 2024-03-19 13:14:35,583 | server.py:91 | Evaluating initial parameters
FL Paper Experiment | INFO flwr 2024-03-19 13:14:35,583 | server.py:104 | FL starting
FL Paper Experiment | DEBUG flwr 2024-03-19 13:14:35,584 | server.py:222 | fit_round 1: strategy sampled 10 clients (out of 20)
FL Paper Experiment | DEBUG flwr 2024-03-19 13:24:15,305 | server.py:236 | fit_round 1 received 10 results and 0 failures
FL Paper Experiment | WARNING flwr 2024-03-19 13:24:16,400 | fedavg.py:250 | No fit_metrics_aggregation_fn provided
FL Paper Experiment | DEBUG flwr 2024-03-19 13:24:16,404 | server.py:173 | evaluate_round 1: strategy sampled 10 clients (out of 20)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:17,662 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 10 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:17,663 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 10 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:18,421 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 19 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:18,422 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 19 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:19,167 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 9 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:19,167 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 9 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:19,987 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 2 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:19,988 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 2 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:20,724 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 8 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:20,724 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 8 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:21,517 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 15 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:21,518 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 15 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:22,209 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:22,210 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:23,126 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 13 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:23,126 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 13 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:24,054 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 7 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:24,055 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 7 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 13:24:24,430 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 12 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 13:24:24,430 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)
AttributeError: module 'torcheval.metrics' has no attribute 'functionak'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=3053, ip=172.18.144.40, actor_id=1bec2c33fa9b673b8d5d397401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f80b41d2650>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 12 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functionak.multiclass_f1_score(outputs, labels, classes)\nAttributeError: module \'torcheval.metrics\' has no attribute \'functionak\'\n',)
FL Paper Experiment | DEBUG flwr 2024-03-19 13:24:24,432 | server.py:187 | evaluate_round 1 received 0 results and 10 failures
FL Paper Experiment | DEBUG flwr 2024-03-19 13:24:24,433 | server.py:222 | fit_round 2: strategy sampled 10 clients (out of 20)
