FL Paper Experiment | INFO flwr 2024-03-19 14:09:45,598 | main.py:35 | 
================================================================================
CIFAR10 - FedProx - NonIID Distribution has started
================================================================================
FL Paper Experiment | INFO flwr 2024-03-19 14:09:45,599 | app.py:178 | Starting Flower simulation, config: ServerConfig(num_rounds=40, round_timeout=None)
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,746 | app.py:213 | Flower VCE: Ray initialized with resources: {'CPU': 6.0, 'node:172.18.144.40': 1.0, 'node:__internal_head__': 1.0, 'memory': 7558749390.0, 'object_store_memory': 3779374694.0}
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,747 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,747 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 4, 'num_gpus': 0}
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,754 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,755 | server.py:89 | Initializing global parameters
FL Paper Experiment | INFO flwr 2024-03-19 14:09:47,755 | server.py:276 | Requesting initial parameters from one random client
FL Paper Experiment | INFO flwr 2024-03-19 14:09:50,743 | server.py:280 | Received initial parameters from one random client
FL Paper Experiment | INFO flwr 2024-03-19 14:09:50,744 | server.py:91 | Evaluating initial parameters
FL Paper Experiment | INFO flwr 2024-03-19 14:09:50,744 | server.py:104 | FL starting
FL Paper Experiment | DEBUG flwr 2024-03-19 14:09:50,744 | server.py:222 | fit_round 1: strategy sampled 10 clients (out of 20)
FL Paper Experiment | DEBUG flwr 2024-03-19 14:18:54,629 | server.py:236 | fit_round 1 received 10 results and 0 failures
FL Paper Experiment | WARNING flwr 2024-03-19 14:18:56,198 | fedavg.py:250 | No fit_metrics_aggregation_fn provided
FL Paper Experiment | DEBUG flwr 2024-03-19 14:18:56,206 | server.py:173 | evaluate_round 1: strategy sampled 10 clients (out of 20)
FL Paper Experiment | ERROR flwr 2024-03-19 14:18:57,970 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([31, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 15 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([31, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:18:57,972 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([31, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 15 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([31, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:18:58,811 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 18 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:18:58,814 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 18 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:18:59,947 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 4 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:18:59,948 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 4 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:00,948 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 19 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:00,949 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 19 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:01,832 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 8 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:01,834 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 8 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:02,904 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 10 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:02,905 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 10 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:03,855 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 16 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:03,856 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 16 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:04,753 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 17 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:04,755 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 17 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:05,655 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 13 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:05,656 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 13 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | ERROR flwr 2024-03-19 14:19:06,076 | ray_client_proxy.py:161 | Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)

FL Paper Experiment | ERROR flwr 2024-03-19 14:19:06,077 | ray_client_proxy.py:162 | [36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate
    return maybe_call_evaluate(
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate
    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)
  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test
    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score
    num_tp, num_label, num_prediction = _f1_score_update(
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update
    _f1_score_update_input_check(input, target, num_classes)
  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check
    raise ValueError(
ValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=787, ip=172.18.144.40, actor_id=f7e73f04a24d00cacb4ac55b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f604526a6b0>)
  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 76, in run\n    job_results = job_fn(client)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 225, in evaluate\n    return maybe_call_evaluate(\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/client.py", line 254, in maybe_call_evaluate\n    return client.evaluate(evaluate_ins)\n  File "/home/leon/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 262, in _evaluate\n    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/Clients.py", line 36, in evaluate\n    loss, accuracy, f1, roc, kappa = test(self.net, self.valloader, DEVICE=self.device)\n  File "/mnt/c/Users/leon1/Documents/Research Repo/Experiments/Ethnicity FL paper/neural_nets.py", line 136, in test\n    f1 += torcheval.metrics.functional.multiclass_f1_score(outputs, labels, num_classes= classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 114, in multiclass_f1_score\n    num_tp, num_label, num_prediction = _f1_score_update(\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 162, in _f1_score_update\n    _f1_score_update_input_check(input, target, num_classes)\n  File "/home/leon/.local/lib/python3.10/site-packages/torcheval/metrics/functional/classification/f1_score.py", line 270, in _f1_score_update_input_check\n    raise ValueError(\nValueError: input should have shape of (num_sample,) or (num_sample, num_classes), got torch.Size([64, 10]).\n',)
FL Paper Experiment | DEBUG flwr 2024-03-19 14:19:06,079 | server.py:187 | evaluate_round 1 received 0 results and 10 failures
FL Paper Experiment | DEBUG flwr 2024-03-19 14:19:06,079 | server.py:222 | fit_round 2: strategy sampled 10 clients (out of 20)
