FL Paper Experiment | INFO flwr 2024-04-17 13:06:29,648 | main.py:26 | 
================================================================================
FedFaces - FedAvgM(accept_failures=True) - 25 clients - IID Distribution has started
================================================================================
FL Paper Experiment | INFO flwr 2024-04-17 13:06:29,649 | app.py:178 | Starting Flower simulation, config: num_rounds=20, no round_timeout
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,953 | app.py:213 | Flower VCE: Ray initialized with resources: {'CPU': 16.0, 'memory': 19586474804.0, 'object_store_memory': 9793237401.0, 'node:192.168.42.149': 1.0, 'node:__internal_head__': 1.0}
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,953 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,953 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0, 'memory': 3221225472}
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,964 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,965 | server.py:92 | [INIT]
FL Paper Experiment | INFO flwr 2024-04-17 13:06:31,965 | server.py:279 | Requesting initial parameters from one random client
FL Paper Experiment | ERROR flwr 2024-04-17 13:06:34,507 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(str(message.metadata.partition_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/Ethnicity-FL-paper/main.py", line 130, in client_fn_CIFAR10_nonIID
    net = _resnet18(classes=10).to(DEVICE)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: _resnet18() missing 1 required positional argument: 'shape'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: _resnet18() missing 1 required positional argument: 'shape'

FL Paper Experiment | ERROR flwr 2024-04-17 13:06:34,507 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(str(message.metadata.partition_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/Ethnicity-FL-paper/main.py", line 130, in client_fn_CIFAR10_nonIID
    net = _resnet18(classes=10).to(DEVICE)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: _resnet18() missing 1 required positional argument: 'shape'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: _resnet18() missing 1 required positional argument: 'shape'
FL Paper Experiment | ERROR flwr 2024-04-17 13:06:34,508 | app.py:313 | [36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(str(message.metadata.partition_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/Ethnicity-FL-paper/main.py", line 130, in client_fn_CIFAR10_nonIID
    net = _resnet18(classes=10).to(DEVICE)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: _resnet18() missing 1 required positional argument: 'shape'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: _resnet18() missing 1 required positional argument: 'shape'
FL Paper Experiment | ERROR flwr 2024-04-17 13:06:34,509 | app.py:314 | Traceback (most recent call last):
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
           ^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/server/server.py", line 483, in run_fl
    hist, elapsed_time = server.fit(
                         ^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/server/server.py", line 93, in fit
    self.parameters = self._get_initial_parameters(server_round=0, timeout=timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/server/server.py", line 282, in _get_initial_parameters
    get_parameters_res = random_client.get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in get_parameters
    message_out = self._submit_job(message, timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 87, in _submit_job
    raise ex
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(str(message.metadata.partition_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/Ethnicity-FL-paper/main.py", line 130, in client_fn_CIFAR10_nonIID
    net = _resnet18(classes=10).to(DEVICE)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: _resnet18() missing 1 required positional argument: 'shape'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=327963, ip=192.168.42.149, actor_id=68328ce55d8ce16b0694190501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f58546214d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/venv/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: _resnet18() missing 1 required positional argument: 'shape'

FL Paper Experiment | ERROR flwr 2024-04-17 13:06:34,509 | app.py:315 | Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 10, 'num_gpus': 0, 'memory': 3221225472} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 10, 'num_gpus': 0, 'memory': 3221225472}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
